before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
dockers:
  - dockerfile: goreleaser/Dockerfile
    image_templates:
    - ghcr.io/benclapp/time_of_use_exporter:latest
    - ghcr.io/benclapp/time_of_use_exporter:v{{ .Major }}
    - ghcr.io/benclapp/time_of_use_exporter:v{{ .Major }}.{{ .Minor }}
    - ghcr.io/benclapp/time_of_use_exporter:{{ .Tag }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
